---
- hosts: all
  gather_facts: False
  tasks:
    - name: Wait for target connection to become reachable
      wait_for_connection:
        timeout: 500

- hosts: all
  become: true
  tasks:
    - name: Install ffmpeg
      shell: |
        cd /usr/local/bin
        mkdir ffmpeg
        cd ffmpeg
        wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
        tar -xf ffmpeg-release-64bit-static.tar.xz
        ln -s /usr/local/bin/ffmpeg/ffmpeg-3.4.1-64bit-static/ffmpeg /usr/bin/ffmpeg
      args:
        creates: /usr/bin/ffmpeg

