---
- hosts: all
  vars:
    work_dir: "/home/{{ username }}/{{ root_dir }}"
  tasks:

    - name: Create directory for app
      file:
        path: "{{ work_dir }}"
        state: directory

    - name: Synchronize source code
      synchronize:
        src: src
        dest: "{{ work_dir }}"

    - name: Copy Go script
      copy:
        src: go
        dest: "{{ work_dir }}/go"
        mode: u+x

    - name: Start Tensorboard
      shell: "ps cax | grep tensorboard || (./go tensorboard > /dev/null 2>&1 &)"
      async: 1000
      poll: 0
      args:
        chdir: "{{ work_dir }}"

    - name: Wait for Tensorboard
      wait_for:
        port: 6006
        delay: 10
